spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/item_bank?characterEncoding=utf8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 1lizhiqiangzz
      initial-size: 1
      min-idle: 1
      max-active: 20
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
    mode: HTML5
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.ggboy.item_bank.beans
